apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/google-samples/microservices-demo/currencyservice, gcr.io/google-samples/microservices-demo/loadgenerator
  name: online-boutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SamWolfs/yomi.git
    targetRevision: HEAD
    path: manifests/online-boutique
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
